package com.fourteen.springboottest.bo.qyt;

/**
 * @author: huangwei
 * @create: 2020/5/29 17:52
 */
public enum Code {
    /**
     * 返回状态码
     */
    SUCCESS(200, "success"),
    BAD_REQUEST(400, "Bad Request"),
    TOKEN_AUTHORIZE_FAIL(401, "Unauthorized"),
    REFRESH_TOKEN_FAIL(403, "Refresh Token Fail"),
    OMP_TOKEN_AUTHORIZE_FAIL(411, "OMP Unauthorized"),
    TOKEN_SOURCE_FAIL(416, "Token Source Error"),
    INNER_SERVICE_FAIL(500, "Internal Server Error"),
    REMOTE_SERVICE_FAIL(503, "Remote Service Unavailable"),
    REMOTE_SERVICE_UNKNOWN(5030, "远端服务器异常"),
    PARAM_JSON_ERROR(4040, "嘉宾参数异常"),
    ENTERPRISE_UID_LACK(5031, "企业UID缺失"),
    GUEST_DEFAULT_LACK(4041, "嘉宾默认信息获取失败"),
    // region 登录异常信息
    LOGIN_INVALID_PICTURE_CODE(900, "验证失败，请拖动滑块将悬浮图像正确拼合"),
    NETWORK_ERROR(901, "网络波动，请稍后重试"),
    LOGIN_ERROR_PHONE(902, "手机号码格式错误"),
    LOGIN_MSG_CODE_SEND_LIMIT(903, "短信验证码发送次数过多，请重新输入"),
    UNKNOWN_PHONE_AREA(904, "归属地未知"),
    LOGIN_INVALID_PARAM(905, "参数非法"),
    LOGIN_CTX_USER_ERROR(906, "图形验证码与用户信息不符"),
    LOGIN_PICTURE_CODE_LIMIT(907, "刷新图形验证码次数过多，请稍后重试"),
    LOGIN_PICTURE_CODE_EXPIRE(908, "图形验证码已失效，请关闭弹窗重新验证"),
    LOGIN_MSG_CODE_SEND(909, "短信验证码已发送，请勿重试"),
    LOGIN_SEND_MSG_CODE_ERROR(910, "短信验证码发送失败，请稍后重试"),
    LOGIN_MSG_CODE_EXPIRE(911, "短信验证码未发送或已失效，请重新获取"),
    LOGIN_VERIFY_MSG_CODE_ERROR(912, "短信验证码错误，请重新输入"),
    LOGIN_MSG_CODE_VERIFY_LIMIT(913, "输入短信验证码次数过多，请稍后重试"),
    LOGIN_DELETED_ACCOUNT(914, "账号已被删除"),
    LOGIN_ACCOUNT_LIMIT(915, "账号已禁用"),
    LOGIN_ACCOUNT_EXPIRE(916, "抱歉，您的账号已不在有效期，请与我司客户经理联系延期。"),
    LOGIN_PASSWORD_ERROR(917, "用户密码不匹配"),
    LOGIN_NO_ACCESS_MODULE(918, "账号没权限访问该模块"),
    NO_PERMISSION(919, "权限不足，请联系客服"),
    LOGIN_NO_CHECK_PICTURE(920, "请先点击图片验证码进行验证"),
    LOGIN_ACCOUNT_PASSWORD_ERROR(921, "账号密码不匹配"),
    LOGIN_TEL_PASSWORD_ERROR(922, "手机号验证码不匹配"),
    LOGIN_SINGLE_DEVICE_ERROR(923, "你的账号已登录设备数超出最大限制，无法登录"),
    INVALID_USER(924, "非法用户"),
    GENERATE_TOKEN_ERROR(925, "获取Token失败"),
    LOGIN_STATE_ERROR(926, "登录信息已失效，请重新登录"),
    LOGIN_DEVICE_LIMIT(927, "您的账号已在别处登录，如非本人登录请联系客服"),
    LOGIN_NO_ACCOUNT(928, "账号不存在"),

    SAME_CONTRACT_NO(929, "同一家公司合同编号不可重复"),
    NO_BASE_STOCK_PLEDGE(930, "股票质押基础数据不存在，无法添加变更数据"),
    NO_SAVE_STOCK_PLEDGE(931, "请先保存，再生成数据"),
    INVALID_DATE(932, "合约结束日期需大于合约开始日期"),
    INVALID_CHANGE_DATE1(933, "合约结束日期需大于合约变动日期"),
    INVALID_CHANGE_DATE2(934, "变更日期需早于最新合同结束日期"),
    INVALID_CHANGE_DATE3(935, "变更日期需晚于上一个变更日期"),
    INVALID_END_DATE(936, "新合约结束日期需晚于当前合约结束日期"),
    INVALID_LINE(937, "输入项需满足该条件：终止线<平仓线<警戒线"),
    INVALID_STK_NUM(938, "输入项需满足该条件：质押股数*现价>=规模"),
    INVALID_CHANGE_STK_NUM(939, "解质押数量不可大于现有质押股数"),
    INVALID_CHANGE_SIZE(940, "偿还本金不可大于现有融资规模"),

    REFERRAL_LINK_ADD_LIMIT(941, "抱歉，推荐位最多添加3篇文章"),
    PRIZE_USER_EXIST(942, "该用户已经发奖，不能再次发奖"),
    PRIZE_CHOOSE_EMPTY(943, "奖品已经发完，请重新选择奖品"),
    PRIZE_ALL_EMPTY(944, "全部奖品已经发完，请重新调整中奖名单"),
    POSTINFO_LOSS(945, "请先填写完全部邮寄信息后才能结束发奖"),
    DATE_UNREACHED(946, "结束失败，请在活动结束七日后再结束发奖"),
    VER_CODE_NOT_EXIST(947, "验证码不存在或已失效"),
    VER_CODE_NOT_MATCH(948, "验证码输入错误"),
    ENT_NO_CHANGE_RESULT(949, "未查询到修改记录"),
    PHONE_VER_OPERA_TOO_OFTEN(950, "验证码发送频繁，请稍后再试"),
    ACC_INFO_IN_AUDIT(951, "资料审核中，请稍后重试"),
    POP_RANK_NO_DATA(952, "当前暂无本公司人气排名数据，如有需求请联系服务经理。"),

    //资讯订阅与报告导出
    SUBSCRIBE_PLAN_NAME_REPEAT(953, "订阅方案名称重复，请重新填写"),
    PLEASE_OPEN_PUSH_SETTING(954, "请开启邮箱订阅或短信订阅或站内推送"),
    EMAIL_FORMAT_ERROR(955, "邮箱格式错误"),
    EMAIL_NUM_LIMIT(956, "最多可绑定5个邮箱"),
    SUBSCRIBE_PLAN_LIMIT(957, "您可创建的定期监测方案已达最大数量，可选择编辑或删除现有方案"),
    PLEASE_CONFIRM_REPORT_PERIOD_SETTING(958, "请确认报告周期及推送时间"),
    REPORT_TIME_SET_ERROR(959, "报告推送时间设置错误"),
    PLEASE_CONFIRM_COMPANY_SETTING(960, "请确认订阅公司及订阅内容"),
    COMPANY_SETTING_NUM_LIMIT(961, "订阅公司最多10家"),
    SMS_SUBSCRIBE_SET_ERROR(962, "短信订阅设置有误"),
    EMAIL_SUBSCRIBE_SET_ERROR(963, "邮箱订阅设置有误"),
    PLAN_NOT_EXIST(964, "订阅方案不存在"),
    PLAN_HAS_DELETED(965, "订阅方案已删除"),
    PLAN_TYPE_MISMATCH(966, "订阅方案类型异常"),
    PLAN_DELETE_FAIL(967, "订阅方案删除失败"),
    PLAN_INSERT_FAIL(968, "订阅方案添加失败"),
    PLAN_EDIT_FAIL(969, "订阅方案编辑失败"),
    PLAN_ENABLE_FAIL(970, "订阅方案启用失败"),
    PLAN_UNENABLE_FAIL(971, "订阅方案停用失败"),
    PLAN_HAS_UNENABLE(972, "订阅方案已停用"),
    PLAN_ENABLE_FAIL_NO_ENABLE_EMAIL_AND_PHONE(973, "订阅方案已停用，没有启用邮箱或手机或站内推送"),

    //BACKEND_ERROR
    // region 登录异常信息
    NO_LOGIN(100, "用户未登录，请先登录"),
    LOGIN_NO_PERMISSION(101, "用户没有操作权限"),
    LOGIN_ERROR_CALL_METHOD_BACKEND(102, "请求的资源不支持该调用方式"),
    NOT_EXIST_ACCOUNT(103, "账号不存在"),
    NOT_EXIST_ROLE(104, "角色不存在"),
    EXIST_ENTERPRISE(105, "该股票代码对应的上市公司已存在，请勿重复创建"),
    NO_COMPANY(106, "未查询到通行证上市公司"),
    NULL_ROLE_MODULES(107, "传入的角色权限为空"),
    EXIST_ACCOUNT(108, "账号名已存在，请重新输入"),
    EXIST_TELEPHONE(109, "手机号已绑定账号，请重新输入"),
    ENT_EXIST_TELEPHONE(1092, "手机号在该公司已绑定账号，请确认"),
    TELEPHONE_UID_CHANGE(1091, "手机号对应的uid已经变化，账号编辑失败"),
    EXIST_ROLE_NAME(110, "角色名已存在，请重新输入"),
    NO_STOCK_INFO(111, "未获取到该股票信息"),
    ROLE_BIND_ACCOUNT(112, "该角色已有用户，不可删除"),
    NOT_EXIST_COMPANY(113, "公司不存在"),
    PERMANENT_NO_EXPIRY_DATE(114, "试用账号必须填写截止日志"),
    NOT_PERMANENT_EXPIRY_DATE(115, "长期有效账号不需填写截止日期"),
    NOT_EXIST_JOIN_COMPANY(116, "未查询到该入驻上市公司"),
    EXIST_JOIN_COMPANY(117, "该通行证uid对应的上市公司已入驻，请勿重复入驻"),
    NO_ASK_ANSWER_CARD(118, "卡片数据不能为空"),
    REPEAT_POST(119, "请勿添加重复的帖子id"),
    PUBLISH_CARD_FAIL(120, "发布问董秘卡片失败"),
    NOT_EXIST_POST(121, "问董秘帖子不存在"),
    MAX_CARD_NUM(122, "预选卡片已满10个，请删除后添加"),
    NOT_EXIST_MENU(123, "菜单不存在或已删除"),
    EXIST_MENU_NAME(124, "菜单名称已存在，请检查重新输入"),
    ERROR_MENU_ORDER(125, "菜单顺序与已有平级菜单顺序重复，请检查后重新输入"),
    NOT_EXIST_DATA(126, "数据不存在"),
    PERCENTAGE_ERROR(127, "百分比数值之和不等于1，请确认数据"),
    EXIST_MENU_AUTH_TAG(128, "菜单权限标识已存在，请检查重新输入"),
    MENU_BIND_ROLE(129, "菜单已绑定角色，不可删除"),

    ACCOUNT_PREFIX_EXISTS(130, "账号前缀已存在"),
    IS_ROLLBACK_TEMPLATE(135, "该模板已撤回"),
    NONCONFORMITY_STATUS(136, "操作失败，请刷新页面重试"),
    DATA_CENTER_NOT_EXIST(131, "数据中台未查询到该公司,请检查后重新输入"),
    EXIST_UID(132, "UID已绑定账号"),

    ENT_EXIST_UID(1321, "UID在该公司已有对应账号，请确认"),
    TRACKING_MAPPING_EXIST(133, "埋点映射关系已存在"),
    TRACKING_MAPPING_NOT_EXIST(134, "埋点映射关系不存在"),
    PUBLISHED_MAPPING_CANNOT_UPDATE_OR_DELETE(135, "已发布的埋点映射关系不可修改和删除"),
    TRACKING_MAPPING_DELETE_FAIL(136, "埋点映射关系删除失败"),
    ONLY_ADMIN_CAN_PUBLISH(137, "仅超级管理员能发布"),
    TRACKING_MAPPING_NOT_CONFIGURE(138, "映射关系还未配置"),
    DO_NOT_REPEAT_PUBLISH(139, "请勿重复发布"),
    TRACKING_MAPPING_PUBLISH_FAIL(136, "埋点映射关系发布失败"),

    GUEST_CONFLICT(143, "路演嘉宾添加冲突"),

    EMPTY_ROLE(144, "用户角色为空"),

    STOCK_CODE_ERROR(137, "股票代码格式错误"),
    STOCK_CODE_SUFFIX_ERROR(138, "股票代码后缀错误"),

    CHOICE_CUSTOMER_ERROR(139, "获取choice客户信息失败"),

    ENTERPRISE_MESSAGE_ERROR(140, "输入的公司信息有误"),
    ENTERPRISE_MESSAGE_lACK(141, "公司通行证uid与股票代码至少存在一个"),

    MARKER_LACK(142, "不存在该市场代码"),

    FAIL(200, "操作失败，请稍后重试"),

    LOGIN_SERVER_ERROR(500, "服务器内部异常"),

    CLASS_NOT_FOUND(1000, "class not found"),
    CRON_ERROR(1001, "cron表达式格式错误"),
    NOT_SUPPORT_SCHEDULE_TYPE(1002, "暂不支持该调度类型"),
    ADD_JOB_FAIL(1003, "添加任务失败"),
    UPDATE_JOB_FAIL(1004, "更新任务失败"),
    JOB_NOT_EXIST(1005, "任务不存在"),
    REMOVE_JOB_FAIL(1006, "删除任务失败"),
    PAUSE_JOB_FAIL(1007, "停止任务失败"),
    RESUME_JOB_FAIL(1008, "恢复任务失败"),
    RESET_JOB_FAIL(1008, "重置任务失败"),

    PACKAGE_NO_AUTH(1101, "沒有可用的服务包权限"),
    PACKAGE_NO_TIME(1102, "权限次数已用尽"),
    PACKAGE_NO_ROLLBACK_ID(1103, "回滚id不正确或已失效"),


    TIME_FORMAT_ERROR(2004, "非法的时间格式"),
    TRACKING_DATA_OVER_SIZE(2005, "PC埋点数据过多，批次同步上限为500"),
    KEYWORDS_MUTEX(2005, "您当前添加的关键词逻辑有误，继续订阅将不存在任何资讯结果"),
    UNKNOWN_DATA_BOARD_TYPE(2006, "未知的数据看板类型"),
    ACTIVE_DATA_NOT_EXIST(2007, "活跃数据详情不存在"),
    USER_NOT_AUTHORIZE(3001, "用户未完成授权"),
    REDIRECT_ROADSHOW_ERROR(3002, "跳转路演中IR服务失败,请稍后重试"),
    REDIRECT_ROADSHOW_NO_MOBILE_ERROR(3003, "跳转路演中IR服务失败,用户未绑定手机号"),
    GET_ENTERPRISE_INFO_ERROR(3004, "获取用户所在公司信息失败"),
    TOKEN_EXPIRE_ERROR(3005, "身份认证已失效，请重新认证"),
    TOKEN_AUTH_ERROR(3006, "身份校验失败"),
    IR_LOGIN_URL_PARAM_ERROR(3007, "手机号和用户唯一标识同时为空或股票代码格式错误"),

    APPLY_FOR_TRIAL_ADD_ERROR(3100, "试用用户信息添加失败"),
    ROAD_SHOW_IR_USER_INFO_ERROR(3101, "路演中用户信息校验失败"),

    ROAD_SHOW_LOGIN_VERIFY(3102, "当前账户需要验证"),
    ROAD_SHOW_INFO_TO_JSON_ERROR(3103, "路演中信息解析失败"),
    EMAIL_PHONE_STATUS(2006, "推送方式不能全部为空"),
    EMAIL_PHONE_ALL_EMPTY(2007, "开启推送，推送方式不能全部为空"),
    EMAIL_VERIFY_FAILURE(2008, "邮箱校验失败，请检查邮箱是否正确"),
    PHONE_VERIFY_FAILURE(2200, "手机号校验失败，请检查手机号是否正确"),
    DAILY_TIME_SETTING_FAILURE(2009, "日报推送时间设置错误"),
    WEEK_TIME_SETTING_FAILURE(2010, "周报推送时间设置错误"),
    MONTH_TIME_SETTING_FAILURE(2020, "月报推送时间设置错误"),
    GUBA_SUBSCRIBE_PLAN_NUM_LIMIT(2011, "您可创建的订阅方案已达最大数量，可选择编辑或删除现有方案"),
    GUBA_PLAN_ADD_FAIL(2012, "订阅方案新增失败"),
    GUBA_PLAN_UPDATE_FAIL(2013, "订阅方案更新失败"),
    GUBA_PLAN_ADD_JOB_FAIL(2014, "订阅方案job新增失败"),
    GUBA_PLAN_UPDATE_JOB_FAIL(2015, "订阅方案job更新失败"),
    GUBA_PLAN_DELETE_FAIL(2016, "订阅方案删除失败"),
    GUBA_PLAN_DELETE_JOB_FAIL(2017, "订阅方案job删除失败"),
    ZX_PLAN_BASE_INFO_SYNC_FAIL(2018, "资讯手机号、邮箱基础信息同步失败"),
    GUBA_PLAN_BASE_INFO_SYNC_FAIL(2019, "股吧手机号、邮箱基础信息同步失败"),
    CAN_NOT_ADD_APPLY_INFO_TODAY(3104, "该账户当天不能再申请试用"),
    NEED_USE_PHONE_LOGIN(3105, "您已开通企业通账号<br/>请试用短信验证码登录!"),
    TOTAL_CLICK_EMPTY(2106, "banner点击总量为空"),
    TENDENCY_EMPTY(2107, "banner点击数据为空"),
    CLICK_DETAIL_EMPTY(2108, "banner点击明细为空"),
    WECHAT_BIND_SUCCESS(3001, "微信绑定成功"),
    WECHAT_UNBIND_SUCCESS(3002, "微信解绑成功"),
    WECHAT_BIND_THIS_ACCOUNT(3003, "微信已绑定该账号"),
    WECHAT_BIND_ANOTHER_ACCOUNT(3004, "微信绑定其他账号"),

    INTERFACE_LIMIT(6001, "该接口处于限流中"),

    PARAMETER_CANNOT_BE_NULL(4001, "参数不能为空"),
    MESSAGE_SETTINGS_EDIT_FAIL(4002, "消息中心修改失败"),
    MESSAGE_SETTINGS_EDIT_STATUS_FAIL(4003, "消息中心修改status失败"),
    DISTURB_TIME_COULD_NOT_BE_NULL(4004, "免打扰时间不能为空"),
    REPORT_PUSH_TIME_ERROR(4005, "报告推送时间格式错误"),
    PUSH_SETTING_OR_PUSH_DATE_ERROR(4006, "请检查推送方式设置或推送日期设置"),
    PUSH_DATE_ERROR(4007, "推送日期设置错误"),
    DISTURB_TIME_COULD_NOT_BE_EQUALS(4008, "开始时间和结束时间不能相同"),
    PLAN_ID_CLOUD_NOT_BE_BLANK(4009, "planId不能为空"),
    VISUALIZATION_RATE_LIMIT(4010, "已有可视化任务分析进行中，请稍后再试"),
    VISUALIZATION_TIME_LIMIT(4011, "最多选择6个月时间分析"),
    RATE_LIMIT(4012, "服务器繁忙，请稍后再试"),
    EXIT_NAME(4013, "公司名称或公司简称已存在"),
    HAVE_CHILDREN_ROLE(4014, "父角色下有子角色时不能删除父角色"),

    ENT_ADMIN_EXIST(4020, "企业管理员数量已达上限"),
    ROLE_CHECK_FAIL(4021, "身份校验失败"),

    FILE_CONTENT_INVALID(4022, "文件内容格式错误"),
    ;


    public final int code;
    public final String msg;

    Code(int code, String msg) {
        this.code = code;
        this.msg = msg;
    }
}
